with cte as 
(
select
	corp_id,
	fac_id,
	location_id,
	line_id,
	equipment_id,
	equipment_name,
	start_dt,
	end_dt,
	person,
	team,
	model_code,
	model_name,
	lot_number,
	input_do,
	machine_number,
	process,
	layer,
	spec,
	ucl,
	lcl,
	spec_result,
	ucl2,
	lcl2,
	spec_result2,
	phanloai,
	seq,
	p1,
	p2,
	p3,
	p4,
	p5,
	p6,
	p7,
	p8,
	p9,
	p10,
	p11,
	p12,
	p13,
	p14,
	p15,
	p16,
	p17,
	p18,
	dolech,
	max_thick,
	min_thick,
	avg_thick,
	spec_result3,
	cpk,
	cpk_check,
	remark,
	extend_dt
from
	dbo.tb_cmi
where 
	  start_dt >= @from_dt and start_dt < @to_dt
	  and end_dt >= @from_dt and end_dt < @to_dt
),
cte2 as 
(
select equipment_id,
	sum(case equipment_id when 'CMI01' then 1 else 0 end) 							as total_01,
	sum(case when equipment_id = 'CMI01' and spec_result ='OK' then 1 else 0 end) 	as OK_01,
	sum(case when equipment_id = 'CMI01' and spec_result ='NG' then 1 else 0 end) 	as NG_01,
	sum(case equipment_id when 'CMI02' then 1 else 0 end) 							as total_02,
	sum(case when equipment_id = 'CMI02' and spec_result ='OK' then 1 else 0 end) 	as OK_02,
	sum(case when equipment_id = 'CMI02' and spec_result ='NG' then 1 else 0 end) 	as NG_02,
	sum(case equipment_id when 'CMI03' then 1 else 0 end) 							as total_03,
	sum(case when equipment_id = 'CMI03' and spec_result ='OK' then 1 else 0 end) 	as OK_03,
	sum(case when equipment_id = 'CMI03' and spec_result ='NG' then 1 else 0 end) 	as NG_03
from dbo.tb_cmi
where 
		start_dt >= @from_dt and start_dt < @to_dt
		and end_dt >= @from_dt and end_dt < @to_dt
group by equipment_id 
)
select
	cte2.total_01,
	cte2.OK_01,   
	cte2.NG_01,   
	cte2.total_02,
	cte2.OK_02,   
	cte2.NG_02,   
	cte2.total_03,
	cte2.OK_03,   
	cte2.NG_03,    
	cte.corp_id,
	cte.fac_id,
	cte.location_id,
	cte.line_id,
	cte.equipment_id,
	cte.equipment_name,
	CONVERT(char(10), cte.start_dt, 23) as start_dt,
	CONVERT(char(10), cte.end_dt, 23) as end_dt,
	cte.person,
	cte.team,
	cte.model_code,
	cte.model_name,
	cte.lot_number,
	cte.input_do,
	cte.machine_number,
	cte.process,
	cte.layer,
	cte.spec,
	cte.ucl,
	cte.lcl,
	cte.spec_result,
	cte.ucl2,
	cte.lcl2,
	cte.spec_result2,
	cte.phanloai,
	cte.seq,
	cte.p1,
	cte.p2,
	cte.p3,
	cte.p4,
	cte.p5,
	cte.p6,
	cte.p7,
	cte.p8,
	cte.p9,
	cte.p10,
	cte.p11,
	cte.p12,
	cte.p13,
	cte.p14,
	cte.p15,
	cte.p16,
	cte.p17,
	cte.p18,
	cte.dolech,
	cte.max_thick,
	cte.min_thick,
	cte.avg_thick,
	cte.spec_result3,
	cte.cpk,
	cte.cpk_check,
	cte.remark,
	cte.extend_dt
from cte
left join 
	cte2
	on cte.equipment_id = cte2.equipment_id
;