SELECT
		SIR.BOM_ITEM_CODE
      , SIR.BOM_ITEM_DESCRIPTION
      , SSR.OPERATION_SEQ_NO
      , SSO.OPERATION_CODE
      , SSO.OPERATION_DESCRIPTION
      , SSW.WORKCENTER_CODE
      , SSW.WORKCENTER_DESCRIPTION
      , SWC.WIP_RESOURCE_CODE
      , SRE.RESOURCE_DESCRIPTION
      , SSE.EQUIPMENT_CODE
      , SSE.EQUIPMENT_DESCRIPTION
      , concat_ws('::',SSO.OPERATION_DESCRIPTION,SSO_tl.OPERATION_DESCRIPTION,'') as tran_lang
FROM dbo.erp_sdm_item_revision SIR 
    INNER      JOIN dbo.erp_sdm_standard_routing    SSR ON SIR.BOM_ITEM_ID = SSR.BOM_ITEM_ID
    INNER      JOIN dbo.erp_sdm_standard_operation  SSO ON SSR.OPERATION_ID = SSO.OPERATION_ID
    LEFT OUTER JOIN dbo.erp_sdm_routing_wip_info    SWC ON SSR.STD_ROUTING_ID = SWC.STD_ROUTING_ID
    LEFT OUTER JOIN dbo.erp_sdm_standard_resource   SRE ON SWC.WIP_RESOURCE_CODE = SRE.RESOURCE_CODE
    LEFT OUTER JOIN dbo.erp_sdm_standard_workcenter SSW ON SRE.WORKCENTER_ID = SSW.WORKCENTER_ID
    LEFT OUTER JOIN dbo.erp_sdm_operation_resource_map MAP ON SSO.OPERATION_ID = MAP.OPERATION_ID
    LEFT OUTER JOIN dbo.erp_sdm_standard_equipment  SSE ON MAP.RESOURCE_ID = SSE.RESOURCE_ID
    JOIN dbo.erp_sdm_standard_operation_tl  SSO_tl ON SSO.OPERATION_ID = SSO_tl.OPERATION_ID
 WHERE SIR.SOB_ID       = 90
   AND SIR.ORG_ID       = 901
   AND SIR.ENABLED_FLAG = 'Y'
   AND SSO.ENABLED_FLAG = 'Y'
   AND SRE.ENABLED_FLAG = 'Y'
   AND SSW.ENABLED_FLAG = 'Y'
   AND SSE.ENABLED_FLAG = 'Y'
   AND MAP.SOB_ID = 90
   AND MAP.ORG_ID = 901
   and SIR.BOM_ITEM_CODE = @model_code
--   AND IIM.ITEM_CATEGORY_CODE = 'FG'
--   AND (SIR.BOM_ITEM_CODE LIKE 'A%' OR SIR.BOM_ITEM_CODE LIKE 'B%')
--   AND SIR.BOM_ITEM_CODE = 'B0100005019-MHA-01'
 ORDER BY SIR.BOM_ITEM_CODE
        , SSR.OPERATION_SEQ_NO
        , SSE.EQUIPMENT_CODE
;