SELECT T.SORT
     , MAX(T.BOM_ITEM_CODE) AS BOM_ITEM_CODE
     , T.BOM_ITEM_DESCRIPTION
     , ROUND(100 - (SUM(T.TOTAL_DEFACT_QTY) / SUM(T.WORK_PCS_QTY) * 100), 1) AS RATE_MONTH
     , (CASE WHEN SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND(100 - (SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.TOTAL_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS RATE_TODAY
     , (CASE WHEN SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND((SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.OPEN_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS OPEN_DEFACT_QTY_TODAY
     , (CASE WHEN SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND((SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.SHORT_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS SHORT_DEFACT_QTY_TODAY
     , (CASE WHEN SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND((SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.ETC_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS ETC_DEFACT_QTY_TODAY
  FROM (
          SELECT APPS.ZF_GET_EXTEND_DATE(TO_DATE(AIH.INSPECT_DATE, 'YYYY-MM-DD HH24:MI:SS')) AS INSPECT_EXTEND_DATE
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , AIH.WORK_PCS_QTY AS WORK_PCS_QTY
               , SUM(CASE WHEN AIL.AOI_DEFECT_CODE = 10            THEN AIL.TOP_DEFACT_QTY + AIL.BOT_DEFACT_QTY ELSE 0 END) AS OPEN_DEFACT_QTY
               , SUM(CASE WHEN AIL.AOI_DEFECT_CODE = 20            THEN AIL.TOP_DEFACT_QTY + AIL.BOT_DEFACT_QTY ELSE 0 END) AS SHORT_DEFACT_QTY
               , SUM(CASE WHEN AIL.AOI_DEFECT_CODE NOT IN (10, 20) THEN AIL.TOP_DEFACT_QTY + AIL.BOT_DEFACT_QTY ELSE 0 END) AS ETC_DEFACT_QTY
               , SUM(AIL.TOP_DEFACT_QTY + AIL.BOT_DEFACT_QTY)                                                               AS TOTAL_DEFACT_QTY
               , ZII.SORT
            FROM APPS.AOI_INSPECT_HEADER AIH 
                INNER JOIN APPS.AOI_INSPECT_LINE  AIL ON AIH.SOB_ID = AIL.SOB_ID AND AIH.ORG_ID = AIL.ORG_ID AND AIH.AOI_INSPECT_HEADER_ID = AIL.AOI_INSPECT_HEADER_ID
                INNER JOIN APPS.QM_COMMON         QCM ON AIH.SOB_ID = QCM.SOB_ID AND AIH.ORG_ID = QCM.ORG_ID AND AIH.DEFECTIVE_LAYER_CODE  = QCM.CODE AND QCM.GROUP_CODE = 'TEST_LAYERS'
                INNER JOIN APPS.SDM_ITEM_REVISION SIR ON AIH.BOM_ITEM_ID = SIR.BOM_ITEM_ID
                INNER JOIN APPS.Z_IMPORTANT_ITEM  ZII ON SIR.INVENTORY_ITEM_ID = ZII.INVENTORY_ITEM_ID
           WHERE AIH.SOB_ID = 90
             AND AIH.ORG_ID = 901
             AND AIH.INSPECT_DATE > TO_CHAR(TRUNC(SYSDATE, 'MM') + INTERVAL '8' HOUR, 'YYYYMMDDHH24MISS')
             AND AOI_DEFECT_CODE != '999'
             AND ZII.LU_ENTRY_ID = 6000003743
           GROUP BY APPS.ZF_GET_EXTEND_DATE(TO_DATE(AIH.INSPECT_DATE, 'YYYY-MM-DD HH24:MI:SS'))
                  , SIR.BOM_ITEM_CODE
                  , SIR.BOM_ITEM_DESCRIPTION
                  , AIH.WORK_PCS_QTY
                  , ZII.SORT
       ) T
 GROUP BY T.SORT
        --, T.BOM_ITEM_CODE
        , T.BOM_ITEM_DESCRIPTION
 ORDER BY T.SORT