-- 0. AOI 수율 월간/주간/금일
SELECT ROUND(100 - (SUM(T.TOTAL_DEFACT_QTY) / SUM(T.WORK_PCS_QTY) * 100), 1) AS RATE_MONTH
     , (CASE WHEN SUM(CASE WHEN TO_CHAR(INSPECT_EXTEND_DATE, 'IW') = TO_CHAR(APPS.ZF_GET_EXTEND_DATE(SYSDATE), 'IW') THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND(100 - (SUM(CASE WHEN TO_CHAR(INSPECT_EXTEND_DATE, 'IW') = TO_CHAR(APPS.ZF_GET_EXTEND_DATE(SYSDATE), 'IW') THEN T.TOTAL_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN TO_CHAR(INSPECT_EXTEND_DATE, 'IW') = TO_CHAR(APPS.ZF_GET_EXTEND_DATE(SYSDATE), 'IW') THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS RATE_WEEK
     , (CASE WHEN SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100 != 0 THEN
                  ROUND(100 - (SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.TOTAL_DEFACT_QTY ELSE 0 END) / SUM(CASE WHEN INSPECT_EXTEND_DATE = APPS.ZF_GET_EXTEND_DATE(SYSDATE) THEN T.WORK_PCS_QTY ELSE 0 END) * 100), 1)
             ELSE 0 END) AS RATE_TODAY
  FROM (
          SELECT APPS.ZF_GET_EXTEND_DATE(TO_DATE(AIH.INSPECT_DATE, 'YYYY-MM-DD HH24:MI:SS')) AS INSPECT_EXTEND_DATE
               , AIH.WORK_PCS_QTY AS WORK_PCS_QTY
               , SUM(AIL.TOP_DEFACT_QTY + AIL.BOT_DEFACT_QTY)                                                               AS TOTAL_DEFACT_QTY
            FROM APPS.AOI_INSPECT_HEADER AIH 
            	INNER JOIN APPS.AOI_INSPECT_LINE  AIL ON AIH.SOB_ID = AIL.SOB_ID AND AIH.ORG_ID = AIL.ORG_ID AND AIH.AOI_INSPECT_HEADER_ID = AIL.AOI_INSPECT_HEADER_ID
           WHERE AIH.SOB_ID = 90
             AND AIH.ORG_ID = 901
             AND AIH.INSPECT_DATE BETWEEN LEAST(TO_CHAR(TRUNC(SYSDATE, 'MONTH'), 'YYYYMMDD') || '080000', TO_CHAR(APPS.ZF_GET_EXTEND_DATE(SYSDATE-1), 'YYYYMMDD') || '080000')
                                      AND TO_CHAR(APPS.ZF_GET_EXTEND_DATE(SYSDATE+1), 'YYYYMMDD') || '075959'
             AND AOI_DEFECT_CODE != '999'
           GROUP BY APPS.ZF_GET_EXTEND_DATE(TO_DATE(AIH.INSPECT_DATE, 'YYYY-MM-DD HH24:MI:SS'))
                  , AIH.WORK_PCS_QTY
       ) T