SELECT IOL.ATTRIBUTE_A AS REJECT_CODE
    ,QMC1.CODE_NAME  AS REJECT_DESC
    ,IOL.REJECT_UOM_CODE
    ,IOL.REJECT_QTY
    ,QMC1.VALUE2 as REJECT_BASE_RATE
    ,IOL.REJECT_RATE
    ,IOL.ATTRIBUTE_1
    ,IOL.ATTRIBUTE_B
    ,QMC2.CODE_NAME  AS ATTRIBUTE_B_DESC
    ,QMC2.VALUE1     AS ATTRIBUTE_B_V1
    ,QMC2.VALUE2     AS ATTRIBUTE_B_V2
    ,QMC2.VALUE3     AS ATTRIBUTE_B_V3
    ,IOL.ATTRIBUTE_C
    ,QMC3.CODE_NAME  AS ATTRIBUTE_C_DESC
    ,IOL.REMARK
FROM erp_qm_inspection_op_header IOH INNER      
    JOIN erp_qm_inspection_op_line IOL  ON IOH.SOB_ID = IOL.SOB_ID  AND IOH.ORG_ID      = IOL.ORG_ID AND IOH.INSPECTION_OP_HEADER_ID = IOL.INSPECTION_OP_HEADER_ID
    LEFT OUTER JOIN erp_qm_common             QMC1 ON IOL.SOB_ID = QMC1.SOB_ID AND IOL.ATTRIBUTE_A = QMC1.CODE  AND QMC1.GROUP_CODE = 'INSPECTOR_Q_CODE'
    LEFT OUTER JOIN erp_qm_common             QMC2 ON IOL.SOB_ID = QMC2.SOB_ID AND IOL.ATTRIBUTE_B = QMC2.CODE  AND QMC2.GROUP_CODE = 'INSPECTOR_P_CODE'
    LEFT OUTER JOIN erp_qm_common             QMC3 ON IOL.SOB_ID = QMC3.SOB_ID AND IOL.ATTRIBUTE_C = QMC3.CODE  AND QMC3.GROUP_CODE = 'INSPECTOR_LOC'
WHERE IOH.JOB_NO = @workorder --@workorder
    AND IOH.IPQC_FLAG = 'B'
    AND IOH.ATTRIBUTE_1 = @oper_seq_no -- 공순
    