SELECT 
	TO_CHAR(SPC.SPC_TIME, 'YY/MM/DD HH24 MI') as SPC_TIME
,		'약품분석' AS CHM_SECTION
,   CASE WHEN NVL(SEF.CTQ_FLAG, 'N') = 'Y' THEN '★' ELSE '' END AS CTQ_FLAG
,		SOC.OP_CLASS_DESCRIPTION 
,		SSE.EQUIPMENT_DESCRIPTION 
,		SEF.FACTOR_CODE
,		SEF.CHEMICAL_NAME 
,		SEF.MEASURE_RANGE 
,		SPC.SPC_VALUE
FROM 
(
--수정완료
--SELECT SEM.EQUIPMENT_ID
--,		 SEM.EQP_CATEGORY_ID
--,		 SEM.SPC_FACTOR_ID
--,	     NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) AS SPC_VALUE
--,	     NVL(SEM.NORMAL_TIME_A,SEM.NORMAL_TIME_D)	AS SPC_TIME
--FROM APPS.SPC_EQP_MEASURE SEM
--INNER JOIN APPS.SPC_EQP_FACTOR   SEF ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
--WHERE SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE)
--    AND  NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
--    														   AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
SELECT 
	SEM.EQUIPMENT_ID
,	SEM.EQP_CATEGORY_ID
,	SEM.SPC_FACTOR_ID
,	NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) AS SPC_VALUE
,	NVL(SEM.NORMAL_TIME_A,SEM.NORMAL_TIME_D)	AS SPC_TIME
FROM 
	APPS.SPC_EQP_MEASURE SEM
INNER JOIN 
	APPS.SPC_EQP_FACTOR SEF 
	ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE 
	SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE)
    AND  NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) NOT BETWEEN NVL(SEF.WARN_MIN_VALUE,0) AND NVL(SEF.WARN_MAX_VALUE,0)
UNION ALL 	
--수정 완료
--SELECT 
--	SEM.EQUIPMENT_ID
--,	SEM.EQP_CATEGORY_ID
--,	SEM.SPC_FACTOR_ID
--,	NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) AS SPC_VALUE
--,	NVL(SEM.NORMAL_TIME_B,SEM.NORMAL_TIME_E)	AS SPC_TIME
--FROM 
--	APPS.SPC_EQP_MEASURE SEM
--INNER JOIN 
--	APPS.SPC_EQP_FACTOR   SEF 
--	ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
--WHERE 
--	SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE) 
--	AND NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
--														 AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
SELECT 
	SEM.EQUIPMENT_ID
,	SEM.EQP_CATEGORY_ID
,	SEM.SPC_FACTOR_ID
,	NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) AS SPC_VALUE
,	NVL(SEM.NORMAL_TIME_B,SEM.NORMAL_TIME_E)	AS SPC_TIME
FROM 
	APPS.SPC_EQP_MEASURE SEM
INNER JOIN 
	APPS.SPC_EQP_FACTOR   SEF 
	ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE 
	SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE) 
	AND NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) NOT BETWEEN NVL(SEF.WARN_MIN_VALUE,0)AND NVL(SEF.WARN_MAX_VALUE,0)
UNION ALL 
-- 수정 완료
--SELECT 
--	SEM.EQUIPMENT_ID
--,	SEM.EQP_CATEGORY_ID
--,	SEM.SPC_FACTOR_ID
--,	NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) AS SPC_VALUE
--,	NVL(SEM.NORMAL_TIME_C,SEM.NORMAL_TIME_F)	AS SPC_TIME
--FROM 
--	APPS.SPC_EQP_MEASURE SEM
--INNER JOIN 
--	APPS.SPC_EQP_FACTOR   SEF 
--	ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
--WHERE 
--	SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE)
--	AND NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
-- 	 													 AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
SELECT 
	SEM.EQUIPMENT_ID
,	SEM.EQP_CATEGORY_ID
,	SEM.SPC_FACTOR_ID
,	NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) AS SPC_VALUE
,	NVL(SEM.NORMAL_TIME_C,SEM.NORMAL_TIME_F)	AS SPC_TIME
FROM 
	APPS.SPC_EQP_MEASURE SEM
INNER JOIN 
	APPS.SPC_EQP_FACTOR   SEF 
	ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE 
	SEM.MEASURE_DATE Between APPS.ZF_GET_EXTEND_DATE(ADD_MONTHS(SYSDATE, -1)) And APPS.ZF_GET_EXTEND_DATE(SYSDATE)
	AND NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) NOT BETWEEN NVL(SEF.WARN_MIN_VALUE,0)AND NVL(SEF.WARN_MAX_VALUE,0)
) SPC
INNER JOIN 
	APPS.SPC_EQP_CATEGORY 		 		SEC 
	ON SEC.EQP_CATEGORY_ID 	= SPC.EQP_CATEGORY_ID 
INNER JOIN
	APPS.SDM_OPERATION_CLASS_TLV 		SOC 
	ON SOC.OP_CLASS_ID 		= SEC.OP_CLASS_ID
INNER JOIN 
	APPS.SDM_STANDARD_EQUIPMENT_TLV 	SSE 
	ON SSE.EQUIPMENT_ID 	= SPC.EQUIPMENT_ID
INNER JOIN 
	APPS.SPC_EQP_FACTOR   				SEF 
	ON SEF.SPC_FACTOR_ID  	= SPC.SPC_FACTOR_ID
WHERE 
	SPC.SPC_TIME IS NOT NULL
	AND SPC.SPC_TIME >= TO_CHAR(:from_dt, 'YYYY-MM-DD') AND SPC.SPC_TIME < TO_CHAR(:to_dt, 'YYYY-MM-DD')
	--AND SPC.SPC_TIME BETWEEN TO_CHAR(:from_dt, 'YYYY-MM-DD') AND TO_CHAR(:to_dt, 'YYYY-MM-DD')
	AND SSE.EQUIPMENT_CODE = :eqp_code
ORDER BY SPC.SPC_TIME DESC
