
-- 이상발생 현황
-- TITLE : 월간 누적 발생 건수
-- COLUMN : 누적 발생 건수, 금일 발생 건수
SELECT SUM(CASE WHEN EXTEND_DATE <= DATEADD(HOUR, -8, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0)) THEN 1 ELSE 0 END) AS MONTH_CNT
     , SUM(CASE WHEN EXTEND_DATE  = DATEADD(HOUR, -8, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0)) THEN 1 ELSE 0 END) AS TODAY_CNT
  FROM erp_qm_inspection_op_header IOH 	INNER      JOIN erp_qm_inspection_op_line IOL  ON IOH.SOB_ID = IOL.SOB_ID  AND IOH.ORG_ID      = IOL.ORG_ID AND IOH.INSPECTION_OP_HEADER_ID = IOL.INSPECTION_OP_HEADER_ID
                                   		LEFT OUTER JOIN erp_qm_common QMC1 ON IOL.SOB_ID = QMC1.SOB_ID AND IOL.ATTRIBUTE_A = QMC1.CODE  AND QMC1.GROUP_CODE = 'INSPECTOR_Q_CODE'
 WHERE IOH.EXTEND_DATE BETWEEN DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AND DATEADD(HOUR, -8, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0))
   AND IOH.IPQC_FLAG = 'B'
   AND isnull(IOL.REJECT_RATE, 0) > isnull(cast(QMC1.VALUE2 as DECIMAL(10,2)) ,0)
;

-- TITLE : 월간 누적 발생 건수(상세)
-- COLUMN : 모델명, 작업지시서번호, 공순, 공정명, 불량명, 불량률(%)
SELECT ROW_NUMBER() OVER(ORDER BY ROUND(IOL.REJECT_RATE, 2) DESC) AS ROW_NUM
     , SIR.BOM_ITEM_DESCRIPTION
     , IOH.JOB_NO
     , IOH.ATTRIBUTE_1 AS OPERATION_SEQ_NO
     , SSO.OPERATION_DESCRIPTION
     , QMC1.CODE_NAME AS REJECT_DESC
     , CASE When ROUND(IOL.REJECT_RATE, 2) > 100 THEN 100 ELSE ROUND(IOL.REJECT_RATE, 2) END AS REJECT_RATE
  FROM erp_qm_inspection_op_header IOH 	INNER      JOIN erp_sdm_item_revision      SIR  ON IOH.BOM_ITEM_ID = SIR.BOM_ITEM_ID
                                   		INNER      JOIN erp_sdm_standard_operation SSO  ON IOH.OPERATION_ID = SSO.OPERATION_ID
                                   		INNER      JOIN erp_qm_inspection_op_line  IOL  ON IOH.SOB_ID = IOL.SOB_ID  AND IOH.ORG_ID      = IOL.ORG_ID AND IOH.INSPECTION_OP_HEADER_ID = IOL.INSPECTION_OP_HEADER_ID
                                   		LEFT OUTER JOIN erp_qm_common              QMC1 ON IOL.SOB_ID = QMC1.SOB_ID AND IOL.ATTRIBUTE_A = QMC1.CODE  AND QMC1.GROUP_CODE = 'INSPECTOR_Q_CODE'
 WHERE IOH.IPQC_FLAG = 'B'
   AND IOH.EXTEND_DATE BETWEEN DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AND DATEADD(HOUR, -8, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0))
   AND isnull(IOL.REJECT_RATE, 0) > isnull(cast(QMC1.VALUE2 as DECIMAL(10,2)) ,0)
;


-- TITLE : 금일 누적 발생 건수(상세)
-- COLUMN : 모델명, 작업지시서번호, 공순, 공정명, 불량명, 불량률(%)
SELECT ROW_NUMBER() OVER(ORDER BY ROUND(IOL.REJECT_RATE, 2) DESC) AS ROW_NUM
     , SIR.BOM_ITEM_DESCRIPTION
     , IOH.JOB_NO
     , IOH.ATTRIBUTE_1 AS OPERATION_SEQ_NO
     , SSO.OPERATION_DESCRIPTION
     , QMC1.CODE_NAME AS REJECT_DESC
     , CASE When ROUND(IOL.REJECT_RATE, 2) > 100 THEN 100 ELSE ROUND(IOL.REJECT_RATE, 2) END AS REJECT_RATE
  FROM erp_qm_inspection_op_header IOH 	INNER      JOIN erp_sdm_item_revision      SIR  ON IOH.BOM_ITEM_ID = SIR.BOM_ITEM_ID
                                   		INNER      JOIN erp_sdm_standard_operation SSO  ON IOH.OPERATION_ID = SSO.OPERATION_ID
                                   		INNER      JOIN erp_qm_inspection_op_line  IOL  ON IOH.SOB_ID = IOL.SOB_ID  AND IOH.ORG_ID      = IOL.ORG_ID AND IOH.INSPECTION_OP_HEADER_ID = IOL.INSPECTION_OP_HEADER_ID
                                   		LEFT OUTER JOIN erp_qm_common              QMC1 ON IOL.SOB_ID = QMC1.SOB_ID AND IOL.ATTRIBUTE_A = QMC1.CODE  AND QMC1.GROUP_CODE = 'INSPECTOR_Q_CODE'
 WHERE IOH.IPQC_FLAG = 'B'
   AND IOH.EXTEND_DATE = DATEADD(HOUR, -8, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0))
   AND isnull(IOL.REJECT_RATE, 0) > isnull(cast(QMC1.VALUE2 as DECIMAL(10,2)) ,0)
;

