SELECT TO_CHAR(SPC.SPC_TIME, 'HH24:MI') as SPC_TIME
,		'약품분석' AS CHM_SECTION  
,		SOC.OP_CLASS_DESCRIPTION 
,		SSE.EQUIPMENT_DESCRIPTION 
,		SEF.FACTOR_CODE
,		SEF.CHEMICAL_NAME 
,		SEF.MEASURE_RANGE 
,		SPC.SPC_VALUE
FROM 
(
SELECT SEM.EQUIPMENT_ID
,		 SEM.EQP_CATEGORY_ID
,		 SEM.SPC_FACTOR_ID
,	     NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) AS SPC_VALUE
,	     NVL(SEM.NORMAL_TIME_A,SEM.NORMAL_TIME_D)	AS SPC_TIME
FROM APPS.SPC_EQP_MEASURE SEM
INNER JOIN APPS.SPC_EQP_FACTOR   SEF ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE SEM.MEASURE_DATE = TRUNC(SYSDATE-1)
    AND  NVL(SEM.NORMAL_VALUE_A,SEM.NORMAL_VALUE_D) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
    														   AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
UNION ALL 	
SELECT SEM.EQUIPMENT_ID
,		 SEM.EQP_CATEGORY_ID
,		 SEM.SPC_FACTOR_ID
,	     NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) AS SPC_VALUE
,	     NVL(SEM.NORMAL_TIME_B,SEM.NORMAL_TIME_E)	AS SPC_TIME
FROM APPS.SPC_EQP_MEASURE SEM
INNER JOIN APPS.SPC_EQP_FACTOR   SEF ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE SEM.MEASURE_DATE = TRUNC(SYSDATE-1) 
AND NVL(SEM.NORMAL_VALUE_B,SEM.NORMAL_VALUE_E) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
														 AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
UNION ALL 
SELECT SEM.EQUIPMENT_ID
,		 SEM.EQP_CATEGORY_ID
,		 SEM.SPC_FACTOR_ID
,	     NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) AS SPC_VALUE
,	     NVL(SEM.NORMAL_TIME_C,SEM.NORMAL_TIME_F)	AS SPC_TIME
FROM APPS.SPC_EQP_MEASURE SEM
INNER JOIN APPS.SPC_EQP_FACTOR   SEF ON SEF.SPC_FACTOR_ID  = SEM.SPC_FACTOR_ID
WHERE SEM.MEASURE_DATE = TRUNC(SYSDATE-1)
AND NVL(SEM.NORMAL_VALUE_C,SEM.NORMAL_VALUE_F) NOT BETWEEN NVL(SEF.NORMINAL_VALUE,0) - NVL(SEF.TOL_LSL_VALUE,0) 
 	 													 AND NVL(SEF.NORMINAL_VALUE,0) + NVL(SEF.TOL_USL_VALUE,0)
) SPC
INNER JOIN APPS.SPC_EQP_CATEGORY 		 		SEC ON SEC.EQP_CATEGORY_ID 	= SPC.EQP_CATEGORY_ID 
INNER JOIN APPS.SDM_OPERATION_CLASS_TLV 		SOC ON SOC.OP_CLASS_ID 		= SEC.OP_CLASS_ID
INNER JOIN APPS.SDM_STANDARD_EQUIPMENT_TLV 	SSE ON SSE.EQUIPMENT_ID 	= SPC.EQUIPMENT_ID
INNER JOIN APPS.SPC_EQP_FACTOR   				SEF ON SEF.SPC_FACTOR_ID  	= SPC.SPC_FACTOR_ID 
ORDER BY SPC.SPC_TIME DESC