-- SPC
SELECT INSPECTION_TIME
     , TYPE_DESC
     , OPERATION_DESCRIPTION
     , BOM_ITEM_CODE
     , BOM_ITEM_DESCRIPTION
     , JOB_NO
     , AFFECT_PNL
     , NG_DESCRIPTION
     , INNER_STANDARD_MIN
     , INNER_STANDARD_MAX
     , (CASE WHEN INNER_STANDARD_MIN - VALUE_LEAST > VALUE_GREATEST - INNER_STANDARD_MAX THEN VALUE_LEAST
                                                                                         ELSE VALUE_GREATEST END) AS VALUE_NG
 FROM (
          SELECT IOH.INSPECTION_DATE
               , TO_CHAR(IOH.INSPECTION_DATE, 'HH24:MI') AS INSPECTION_TIME
               , 'IPQC 치수검사' AS TYPE_DESC
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , IOH.JOB_NO
               , '' AS AFFECT_PNL
               , LE.ENTRY_DESCRIPTION ||
                 CASE WHEN LE2.ENTRY_DESCRIPTION IS NOT NULL THEN LE2.ENTRY_DESCRIPTION ELSE '' END ||
                 CASE WHEN LE3.ENTRY_DESCRIPTION IS NOT NULL THEN LE3.ENTRY_DESCRIPTION ELSE '' END     AS NG_DESCRIPTION
               , IOC.INNER_STANDARD_MIN
               , IOC.INNER_STANDARD_MAX
               --, IOC.STATUS_CUSTOMER -- [고객기준 상태] ADD, 2022-06-13, BY JHHAN
               , LEAST(NVL(IOC.N_VALUE1,999999999), NVL(IOC.N_VALUE2,999999999), NVL(IOC.N_VALUE3,999999999), NVL(IOC.N_VALUE4,999999999), NVL(IOC.N_VALUE5,999999999), NVL(IOC.N_VALUE6,999999999), NVL(IOC.N_VALUE7,999999999), NVL(IOC.N_VALUE8,999999999), NVL(IOC.N_VALUE9,999999999), NVL(IOC.N_VALUE10,999999999), NVL(IOC.N_VALUE11,999999999), NVL(IOC.N_VALUE12,999999999), NVL(IOC.N_VALUE13,999999999), NVL(IOC.N_VALUE14,999999999), NVL(IOC.N_VALUE15,999999999), NVL(IOC.N_VALUE16,999999999), NVL(IOC.N_VALUE17,999999999), NVL(IOC.N_VALUE18,999999999), NVL(IOC.N_VALUE19,999999999), NVL(IOC.N_VALUE20,999999999)) AS VALUE_LEAST
               , GREATEST(NVL(IOC.N_VALUE1,-999999999), NVL(IOC.N_VALUE2,-999999999), NVL(IOC.N_VALUE3,-999999999), NVL(IOC.N_VALUE4,-999999999), NVL(IOC.N_VALUE5,-999999999), NVL(IOC.N_VALUE6,-999999999), NVL(IOC.N_VALUE7,-999999999), NVL(IOC.N_VALUE8,-999999999), NVL(IOC.N_VALUE9,-999999999), NVL(IOC.N_VALUE10,-999999999), NVL(IOC.N_VALUE11,-999999999), NVL(IOC.N_VALUE12,-999999999), NVL(IOC.N_VALUE13,-999999999), NVL(IOC.N_VALUE14,-999999999), NVL(IOC.N_VALUE15,-999999999), NVL(IOC.N_VALUE16,-999999999), NVL(IOC.N_VALUE17,-999999999), NVL(IOC.N_VALUE18,-999999999), NVL(IOC.N_VALUE19,-999999999), NVL(IOC.N_VALUE20,-999999999)) AS VALUE_GREATEST
            FROM APPS.QM_INSPECTION_OP_HEADER IOH 
            	INNER      JOIN APPS.QM_INSPECTION_OP_CS    IOC ON IOH.INSPECTION_OP_HEADER_ID = IOC.INSPECTION_OP_HEADER_ID
                INNER      JOIN APPS.SDM_STANDARD_OPERATION SSO ON IOH.OPERATION_ID = SSO.OPERATION_ID
                INNER      JOIN APPS.SDM_ITEM_REVISION      SIR ON SIR.BOM_ITEM_ID = IOH.BOM_ITEM_ID 
                LEFT OUTER JOIN APPS.EAPP_LOOKUP_ENTRY      LE  ON IOC.CHECK_TYPE_ID           = LE.LOOKUP_ENTRY_ID
                LEFT OUTER JOIN APPS.EAPP_LOOKUP_ENTRY      LE2 ON IOC.CHECK_POSITION_ID       = LE2.LOOKUP_ENTRY_ID
                LEFT OUTER JOIN APPS.EAPP_LOOKUP_ENTRY      LE3 ON IOC.CHECK_NUMBER_ID         = LE3.LOOKUP_ENTRY_ID
           WHERE IOH.SOB_ID = 90
             AND IOH.ORG_ID = 901
             AND IOH.IPQC_FLAG = 'A'
             AND IOH.EXTEND_DATE BETWEEN APPS.ZF_GET_EXTEND_DATE(SYSDATE - 1) AND APPS.ZF_GET_EXTEND_DATE(SYSDATE)
             AND IOC.STATUS = 'NG'
             AND IOC.N_VALUE1 IS NOT NULL             
        UNION ALL      
             -- 신뢰성 (신뢰성 등록 데이터 중 공정타입코드 V06)
          SELECT MRH.INSPECTION_DATE
               , TO_CHAR(MRH.CREATION_DATE, 'HH24:MI') AS INSPECTION_TIME
               , '신뢰성 검사' AS TYPE_DESC
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , MRH.JOB_NO
               , '' AS AFFECT_PNL
               , QC.CODE_NAME||'-' || QC2.CODE_NAME    AS NG_DESCRIPTION
               , NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999) AS INNER_STANDARD_MIN
               , NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999) AS INNER_STANDARD_MAX
               , MIN(MRL.COLUMN_VALUE) AS VALUE_LEAST
               , MAX(MRL.COLUMN_VALUE) AS VALUE_GREATEST
            FROM APPS.Z_MES_RELIABILITY_HEADER MRH 
            	INNER      JOIN APPS.Z_MES_RELIABILITY_LINE      MRL ON MRH.RELIABILITY_HEADER_ID  = MRL.RELIABILITY_HEADER_ID 
                INNER      JOIN APPS.SDM_STANDARD_OPERATION 	  SSO ON MRH.OPERATION_ID 			= SSO.OPERATION_ID
                INNER      JOIN APPS.SDM_ITEM_REVISION           SIR ON MRH.BOM_ITEM_ID 			= SIR.BOM_ITEM_ID
                INNER      JOIN APPS.Z_MES_RELIABILITY_ITEM      MRI ON MRI.RELIABILITY_ITEM_ID    = MRH.RELIABILITY_ITEM_ID 
                LEFT OUTER JOIN APPS.QM_COMMON               QC  ON MRI.MES_Y_FACTOR_ID        = QC.COMMON_ID 
                LEFT OUTER JOIN APPS.QM_COMMON      	  	  QC2 ON MRI.MES_Y_FACTOR_DTL_ID    = QC2.COMMON_ID 
           WHERE SSO.SOB_ID = 90 AND SSO.ORG_ID =901
             AND SSO.OPERATION_TYPE_ID = 199 -- 공정 타입 [유산동/V06], 신뢰성 검사 공정
             AND MRH.INSPECTION_DATE BETWEEN APPS.ZF_GET_EXTEND_DATE(SYSDATE - 1) AND APPS.ZF_GET_EXTEND_DATE(SYSDATE)             
             AND MRL.COLUMN_VALUE IS NOT NULL
          HAVING (MIN(MRL.COLUMN_VALUE) < NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999) 
          		  OR MAX(MRL.COLUMN_VALUE) > NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999)) -- 검사 데이터 기준 결과 NG체크
           GROUP BY MRH.INSPECTION_DATE
               , TO_CHAR(MRH.CREATION_DATE, 'HH24:MI')             
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , MRH.JOB_NO
               , QC.CODE_NAME
               , QC2.CODE_NAME
               , NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999)
               , NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999)
        UNION ALL      
             -- 출하검사 (신뢰성 등록 데이터 중 공정타입코드 S03 )
          SELECT MRH.INSPECTION_DATE
               , TO_CHAR(MRH.CREATION_DATE, 'HH24:MI') AS INSPECTION_TIME
               , '출하검사' AS TYPE_DESC
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , MRH.JOB_NO
               , '' AS AFFECT_PNL
               , QC.CODE_NAME||'-' || QC2.CODE_NAME    AS NG_DESCRIPTION
               , NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999) AS INNER_STANDARD_MIN
               , NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999) AS INNER_STANDARD_MAX
               , MIN(MRL.COLUMN_VALUE) AS VALUE_LEAST
               , MAX(MRL.COLUMN_VALUE) AS VALUE_GREATEST
            FROM APPS.Z_MES_RELIABILITY_HEADER MRH 
            	INNER      JOIN APPS.Z_MES_RELIABILITY_LINE      MRL ON MRH.RELIABILITY_HEADER_ID  = MRL.RELIABILITY_HEADER_ID 
                INNER      JOIN APPS.SDM_STANDARD_OPERATION 	  SSO ON MRH.OPERATION_ID 			= SSO.OPERATION_ID
                INNER      JOIN APPS.SDM_ITEM_REVISION           SIR ON MRH.BOM_ITEM_ID 			= SIR.BOM_ITEM_ID
                INNER      JOIN APPS.Z_MES_RELIABILITY_ITEM      MRI ON MRI.RELIABILITY_ITEM_ID    = MRH.RELIABILITY_ITEM_ID 
                LEFT OUTER JOIN APPS.QM_COMMON               QC  ON MRI.MES_Y_FACTOR_ID        = QC.COMMON_ID 
                LEFT OUTER JOIN APPS.QM_COMMON      	  	  QC2 ON MRI.MES_Y_FACTOR_DTL_ID    = QC2.COMMON_ID 
           WHERE SSO.SOB_ID = 90 AND SSO.ORG_ID =901
             AND SSO.OPERATION_TYPE_ID = 191 -- 공정 타입 [베트남선적/S03], 출하 검사 공정
             AND MRH.INSPECTION_DATE BETWEEN APPS.ZF_GET_EXTEND_DATE(SYSDATE - 1) AND APPS.ZF_GET_EXTEND_DATE(SYSDATE)             
             AND MRL.COLUMN_VALUE IS NOT NULL
          HAVING (MIN(MRL.COLUMN_VALUE) < NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999) 
          		  OR MAX(MRL.COLUMN_VALUE) > NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999)) -- 검사 데이터 기준 결과 NG체크
           GROUP BY MRH.INSPECTION_DATE
               , TO_CHAR(MRH.CREATION_DATE, 'HH24:MI')             
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , MRH.JOB_NO
               , QC.CODE_NAME
               , QC2.CODE_NAME
               , NVL(MRH.SPEC,0) - NVL(MRH.SPEC_MINUS_TOL,999999999)
               , NVL(MRH.SPEC,0) + NVL(MRH.SPEC_PLUS_TOL,999999999)
         UNION ALL      
             -- 외주 수입검사 (IQC 치수 데이터)
          SELECT QIJ.INSPECT_DATE
               , TO_CHAR(QIJ.INSPECT_DATE , 'HH24:MI') AS INSPECTION_TIME
               , 'IQC 치수 검사' AS TYPE_DESC
               , SSO.OPERATION_DESCRIPTION
               , SIR.BOM_ITEM_CODE
               , SIR.BOM_ITEM_DESCRIPTION
               , QIJ.JOB_NO
               , '' AS AFFECT_PNL
               , '치수'    AS NG_DESCRIPTION
               , NVL(QIS.SPEC,0) - NVL(QIS.SPEC_MINUS ,999999999) AS INNER_STANDARD_MIN
               , NVL(QIS.SPEC,0) + NVL(QIS.SPEC_PLUS,999999999) AS INNER_STANDARD_MAX
               , LEAST(NVL(QIM.DATA_01,999999999), NVL(QIM.DATA_02,999999999), NVL(QIM.DATA_03,999999999), NVL(QIM.DATA_04,999999999), NVL(QIM.DATA_05,999999999)) AS VALUE_LEAST
               , GREATEST(NVL(QIM.DATA_01,-999999999), NVL(QIM.DATA_02,-999999999), NVL(QIM.DATA_03,-999999999), NVL(QIM.DATA_04,-999999999), NVL(QIM.DATA_05,-999999999)) AS VALUE_GREATEST
            FROM APPS.QM_OUT_IQC_MEASURE QIM 
            	INNER      JOIN APPS.QM_OUT_IQC_SPEC           QIS ON QIM.QM_OUT_IQC_SPEC_ID      = QIS.QM_OUT_IQC_SPEC_ID
            	INNER      JOIN APPS.QM_OUT_INSPECT_JOB 	      QIJ ON QIJ.OUT_INSPECT_ID 	 	 = QIM.OUT_INSPECT_ID            							 
            	INNER	   JOIN	APPS.WIP_OUT_RECEIPT_OPERATION RO  ON RO.RECEIPT_OP_ID 			 = QIJ.OUT_RECEIPT_ID
	            INNER      JOIN APPS.SDM_STANDARD_OPERATION 	  SSO ON RO.OPERATION_ID  			 = SSO.OPERATION_ID
	            INNER      JOIN APPS.SDM_ITEM_REVISION         SIR ON QIJ.BOM_ITEM_ID  			 = SIR.BOM_ITEM_ID
           WHERE  QIJ.INSPECT_DATE BETWEEN APPS.ZF_GET_EXTEND_DATE(SYSDATE - 10) AND APPS.ZF_GET_EXTEND_DATE(SYSDATE)             
             AND QIM.DATA_01 IS NOT NULL
             AND QIM.PASS_FLAG_AT_INSPECTION = 'NG'

      ) T
 ORDER BY T.INSPECTION_DATE DESC